"""Compatibility shim for the split ``pi-agent-harness`` package."""

try:
    from pi_agent_harness import (
        ActiveToolsChangeEntry,
        AgentHarness,
        AgentHarnessError,
        AgentHarnessResources,
        AgentHarnessStreamOptions,
        AssistantMessage,
        BranchSummaryEntry,
        BranchSummaryError,
        CompactionEntry,
        CompactionError,
        CustomEntry,
        CustomMessageEntry,
        ExecutionError,
        FileError,
        FileInfo,
        JsonlSessionMetadata,
        JsonlSessionRepo,
        JsonlSessionStorage,
        JsonlStorageFs,
        LabelEntry,
        LeafEntry,
        MemorySessionRepo,
        MemorySessionStorage,
        MessageEntry,
        ModelChangeEntry,
        Session,
        SessionContext,
        SessionError,
        SessionInfoEntry,
        SessionMetadata,
        SessionStorage,
        SessionTreeEntry,
        ThinkingLevelChangeEntry,
        ToolResultMessage,
        UserMessage,
        build_session_context,
        load_jsonl_session_metadata,
        uuid7,
    )
except ImportError as exc:  # pragma: no cover - only hit when harness is not installed.
    raise ImportError(
        "pi_agent_core.harness has moved to the optional pi-agent-harness package. "
        "Install pi-agent-harness and import from pi_agent_harness."
    ) from exc

__all__ = [
    "ActiveToolsChangeEntry",
    "AgentHarness",
    "AgentHarnessError",
    "AgentHarnessResources",
    "AgentHarnessStreamOptions",
    "AssistantMessage",
    "BranchSummaryEntry",
    "BranchSummaryError",
    "CompactionEntry",
    "CompactionError",
    "CustomEntry",
    "CustomMessageEntry",
    "ExecutionError",
    "FileError",
    "FileInfo",
    "JsonlSessionMetadata",
    "JsonlSessionRepo",
    "JsonlSessionStorage",
    "JsonlStorageFs",
    "LabelEntry",
    "LeafEntry",
    "MemorySessionRepo",
    "MemorySessionStorage",
    "MessageEntry",
    "ModelChangeEntry",
    "Session",
    "SessionContext",
    "SessionError",
    "SessionInfoEntry",
    "SessionMetadata",
    "SessionStorage",
    "SessionTreeEntry",
    "ThinkingLevelChangeEntry",
    "ToolResultMessage",
    "UserMessage",
    "build_session_context",
    "load_jsonl_session_metadata",
    "uuid7",
]
