schema_version = "1.1"
artifacts = []

[task]
name = "terminal-bench/sqlite-db-truncate"
description = "Evaluates the ability to recover data from a corrupted SQLite database using binary file analysis and data recovery techniques."
keywords = ["file-operations", "debugging"]
[[task.authors]]
name = "Nicholas Carlini"
email = "nicholas@carlini.com"

[metadata]
author_name = "Nicholas Carlini"
author_email = "nicholas@carlini.com"
difficulty = "medium"
category = "debugging"
tags = ["file-operations"]
expert_time_estimate_min = 60.0
junior_time_estimate_min = 240.0

[verifier]
timeout_sec = 900.0

[agent]
timeout_sec = 900.0

[environment]
build_timeout_sec = 600.0
docker_image = "alexgshaw/sqlite-db-truncate:20251031"
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]

[environment.env]

[solution.env]
