[package]
license = "Apache-2.0"
edition.workspace = true
name = "pi-tracing"
version = "0.1.0"

[dependencies]
async-trait = { workspace = true }
http = { workspace = true }
log = { workspace = true }
fastrace = { workspace = true }
fastrace-tonic = { workspace = true }
fastrace-opentelemetry = { workspace = true }
fastrace-reqwest = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-http = { workspace = true }
opentelemetry-otlp = { workspace = true }
opentelemetry_sdk = { workspace = true, features = ["testing"] }
reqwest = { workspace = true }
reqwest-middleware = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tower = { workspace = true, features = ["full"] }
tower-http = { workspace = true, features = ["trace"] }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
bytes = { workspace = true }
http-body-util = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing-subscriber = { workspace = true }
wiremock = { workspace = true }

[lints]
workspace = true
